ALTER TABLE "anime_followed" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "mal_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "image" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "aired" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "title" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "anime_followed" ALTER COLUMN "followed_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "mal_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "image" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "title" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "light_novel_followed" ALTER COLUMN "followed_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mangas_followed" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mangas_followed" ALTER COLUMN "mal_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mangas_followed" ALTER COLUMN "image" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mangas_followed" ALTER COLUMN "type" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mangas_followed" ALTER COLUMN "title" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mangas_followed" ALTER COLUMN "followed_at" SET NOT NULL;